"""add_point_balance_and_transactions

Revision ID: f18f84939a98
Revises: 17cbce905d8c
Create Date: 2026-04-01 01:00:28.218036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18f84939a98'
down_revision: Union[str, None] = '17cbce905d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CHARGE', 'CONSUME', 'REFUND', 'ADMIN_GRANT', name='pointtransactiontype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_transactions_user_id'), 'point_transactions', ['user_id'], unique=False)
    op.add_column('interview_questions', sa.Column('points_consumed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interview_sessions', sa.Column('total_questions', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interview_sessions', sa.Column('total_follow_ups', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('interview_sessions', sa.Column('total_points_spent', sa.Integer(), nullable=False, server_default='0'))
    op.drop_constraint('interview_sessions_project_id_key', 'interview_sessions', type_='unique')
    op.create_index(op.f('ix_interview_sessions_project_id'), 'interview_sessions', ['project_id'], unique=False)
    op.drop_constraint('interview_sessions_payment_id_fkey', 'interview_sessions', type_='foreignkey')
    op.drop_column('interview_sessions', 'payment_id')
    op.drop_column('interview_sessions', 'current_question_index')
    op.drop_column('project_answers', 'revisions_remaining')
    op.add_column('users', sa.Column('point_balance', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'point_balance')
    op.add_column('project_answers', sa.Column('revisions_remaining', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interview_sessions', sa.Column('current_question_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interview_sessions', sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('interview_sessions_payment_id_fkey'), 'interview_sessions', 'payments', ['payment_id'], ['id'])
    op.drop_index(op.f('ix_interview_sessions_project_id'), table_name='interview_sessions')
    op.create_unique_constraint(op.f('interview_sessions_project_id_key'), 'interview_sessions', ['project_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('interview_sessions', 'total_points_spent')
    op.drop_column('interview_sessions', 'total_follow_ups')
    op.drop_column('interview_sessions', 'total_questions')
    op.drop_column('interview_questions', 'points_consumed')
    op.drop_index(op.f('ix_point_transactions_user_id'), table_name='point_transactions')
    op.drop_table('point_transactions')
    # ### end Alembic commands ###
